# Generated by Django 4.2.30 on 2026-04-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0002_alter_comment_id_alter_notification_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('post', 'New Post'), ('ban', 'Ban'), ('unban', 'Unban'), ('mention', 'Mention')], max_length=20),
        ),
    ]
