# Generated by Django 4.2.30 on 2026-05-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0009_moderationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
