# Generated by Django 4.2.30 on 2026-04-24 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('some_app', '0004_topic_moderators_topicban'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicban',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='topicban',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topicban',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='some_app.topic'),
        ),
        migrations.AlterField(
            model_name='topicban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_bans', to=settings.AUTH_USER_MODEL),
        ),
    ]
