# Generated by Django 4.2.30 on 2026-04-26 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('some_app', '0004_section_alter_topic_options_topic_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
