# Generated by Django 4.2.29 on 2026-04-20 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('some_app', '0005_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
