# Generated by Django 4.2.30 on 2026-05-05 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('some_app', '0008_tag_topic_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('edit_topic', 'Edit topic'), ('delete_topic', 'Delete topic'), ('edit_post', 'Edit post'), ('delete_post', 'Delete post'), ('edit_comment', 'Edit comment'), ('delete_comment', 'Delete comment'), ('ban_user', 'Ban user'), ('unban_user', 'Unban user'), ('review_report', 'Review report'), ('resolve_report', 'Resolve report'), ('reject_report', 'Reject report')], max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs_as_target', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='some_app.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
